name: Release

on:
  workflow_dispatch:
  release:
    types: [released]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    if: github.repository == 'spacetelescope/stsynphot_refactor'
    environment:
      name: release
      url: https://pypi.org/p/stsynphot
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
      with:
        python-version: '3.x'

    - name: Install python-build and twine
      run: python -m pip install build "twine>=3.3"

    - name: Build package
      run: python -m build --sdist --wheel .

    - name: List result
      run: ls -l dist

    - name: Check dist
      run: python -m twine check --strict dist/*

    - name: Test package
      run: |
        cd ..
        python -m venv testenv
        testenv/bin/pip install pytest-astropy ci-watson stsynphot_refactor/dist/*.whl
        testenv/bin/python -c "import stsynphot; stsynphot.test()"

    - name: Publish distribution 📦 to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@897895f1e160c830e369f9779632ebc134688e1b  # v1.10.2
